import Fuse from "fuse.js"

/**
 * This functions takes a string as parameter and returns all celebrities from our list whose name is close
 * to the query. It uses Fuse.js which is a powerful, lightweight fuzzy-search library. Fuzzy searching is the
 * technique of finding strings that are approximately equal to a given pattern (our query).
 * @param query - this string will filter the output of our function to return only celebrities close to our input.
 */
export function getAutocompleteSuggestions(query: string): string[] {
    const fuseOptions: Fuse.IFuseOptions<string> = {
        threshold: 0.4,
    }
    // Initialize Fuse with the celebrity data and options and perform search
    const fuse = new Fuse(celebrities, fuseOptions)
    return fuse.search(query).map(result => result.item)
}

export const celebrities: string[] = [
    "Taylor Swift",
    "Albert Einstein",
    "Dua Lipa",
    "Leonardo da Vinci",
    "Michael Jackson",
    "Madonna",
    "Elvis Presley",
    "Beyoncé",
    "Tom Cruise",
    "Angelina Jolie",
    "Brad Pitt",
    "Marilyn Monroe",
    "Barack Obama",
    "Oprah Winfrey",
    "Justin Bieber",
    "Rihanna",
    "Adele",
    "Emma Watson",
    "Kanye West",
    "Lady Gaga",
    "Jennifer Lopez",
    "Will Smith",
    "Britney Spears",
    "Johnny Depp",
    "Selena Gomez",
    "David Beckham",
    "Cristiano Ronaldo",
    "Katy Perry",
    "Steve Jobs",
    "Mark Zuckerberg",
    "Bill Gates",
    "Jeff Bezos",
    "Salvador Dalí",
    "Vincent van Gogh",
    "Walt Disney",
    "Angela Merkel",
    "Kylie Jenner",
    "Kim Kardashian",
    "Kendall Jenner",
    "Stephen Hawking",
    "Snoop Dogg",
    "Eminem",
    "Arnold Schwarzenegger",
    "Michael Jordan",
    "Muhammad Ali",
    "Celine Dion",
    "John Lennon",
    "Paul McCartney",
    "Ringo Starr",
    "George Harrison",
    "Bob Marley",
    "Elton John",
    "Freddie Mercury",
    "David Bowie",
    "Elizabeth II",
    "William, Prince of Wales",
    "Diana, Princess of Wales",
    "Nelson Mandela",
    "Malala Yousafzai",
    "Ellen DeGeneres",
    "Tom Hanks",
    "Robert Downey Jr.",
    "Jennifer Aniston",
    "Meryl Streep",
    "Leonardo DiCaprio",
    "Julia Roberts",
    "George Clooney",
    "Matt Damon",
    "Nicole Kidman",
    "Tom Hardy",
    "Daniel Radcliffe",
    "Emma Stone",
    "Scarlett Johansson",
    "Chris Hemsworth",
    "Jennifer Lawrence",
    "Gigi Hadid",
    "Zendaya",
    "Harry Styles",
    "Lionel Messi",
    "Neymar",
    "Serena Williams",
    "Roger Federer",
    "Lewis Hamilton",
    "Usain Bolt",
    "Tiger Woods",
    "Billie Eilish",
    "Ariana Grande",
    "Megan Fox",
    "Jessica Alba",
    "Gwyneth Paltrow",
    "Emmanuel Macron",
    "François Hollande",
    "Nicolas Sarkozy",
    "Carla Bruni",
    "Édith Piaf",
    "Marion Cotillard",
    "Ryan Reynolds",
    "Blake Lively",
    "Ryan Gosling",
    "Tom Holland",
    "Coco Chanel",
    "Christian Dior",
    "Jacques Brel",
    "Charles Aznavour",
    "Joe Biden",
    "Greta Thunberg",
    "John von Neumann",
    "Haruma Miura",
    "Donald Trump",
    "Elon Musk",
    "Adolf Hitler",
    "Pablo Escobar",
    "Vladimir Putin",
    "Sigmund Freud",
    "Napoleon",
    "Joseph Stalin",
    "Prince Philip, Duke of Edinburgh",
    "Ludwig van Beethoven",
    "Joaquin Phoenix",
    "Dwayne Johnson",
    "Kobe Bryant",
    "Winston Churchill",
    "Alexander the Great",
    "Paul Walker",
    "Frida Kahlo",
    "Bruce Lee",
    "Nikola Tesla",
    "Christopher Columbus",
    "Wolfgang Amadeus Mozart",
    "Keanu Reeves",
    "Queen Victoria",
    "Heath Ledger",
    "Julius Caesar",
    "Mahatma Gandhi",
    "Charles III",
    "Princess Margaret, Countess of Snowdon",
    "Mike Tyson",
    "Jason Statham",
    "Marie Curie",
    "Clint Eastwood",
    "Charles Manson",
    "Martin Luther King Jr.",
    "Zlatan Ibrahimović",
    "George VI",
    "Karl Marx",
    "Boris Johnson",
    "William Shakespeare",
    "Louis XIV",
    "Pope Francis",
    "Margot Robbie",
    "John F. Kennedy",
    "Ted Bundy",
    "Sylvester Stallone",
    "Aristotle",
    "Kirk Douglas",
    "Joaquín \"El Chapo\" Guzmán",
    "Vladimir Lenin",
    "Quentin Tarantino",
    "Elizabeth I",
    "Robin Williams",
    "Che Guevara",
    "Charlize Theron",
    "LeBron James",
    "Pablo Picasso",
    "6ix9ine",
    "Xi Jinping",
    "Pope John Paul II",
    "Naya Rivera",
    "Catherine the Great",
    "Al Pacino",
    "Sharon Tate",
    "Ronaldinho",
    "Isaac Newton",
    "Plato",
    "Shakira",
    "Robert De Niro",
    "Abraham Lincoln",
    "Timothée Chalamet",
    "Benito Mussolini",
    "Amber Heard",
    "Genghis Khan",
    "Tupac Shakur",
    "Patrick Swayze",
    "Socrates",
    "Dennis Rodman",
    "Charlie Chaplin",
    "Michael Schumacher",
    "Galileo Galilei",
    "Anne Frank",
    "Ken Miles",
    "Friedrich Nietzsche",
    "Anne Hathaway",
    "Jackie Chan",
    "Suleiman the Magnificent",
    "Henry VIII",
    "Mary, Queen of Scots",
    "Ennio Morricone",
    "Alexander Lukashenko",
    "Zinedine Zidane",
    "XXXTentacion",
    "Franklin D. Roosevelt",
    "Natalie Portman",
    "Scottie Pippen",
    "Thomas Edison",
    "Yuriko Koike",
    "Johannes Kepler",
    "Pelé",
    "Giuseppe Conte",
    "Pope Benedict XVI",
    "Tedros Adhanom Ghebreyesus",
    "Joan of Arc",
    "Charles Darwin",
    "John Travolta",
    "Edward VIII",
    "Whitney Houston",
    "Judy Garland",
    "Mikhail Gorbachev",
    "Nostradamus",
    "Vin Diesel",
    "Bradley Cooper",
    "Al Capone",
    "Kurt Cobain",
    "Johann Sebastian Bach",
    "Cillian Murphy",
    "The Buddha",
    "Ana de Armas",
    "Carles Puigdemont",
    "Mao Zedong",
    "Ben Affleck",
    "Martin Luther",
    "Akechi Mitsuhide",
    "Audrey Hepburn",
    "Diego Maradona",
    "Jim Carrey",
    "Charlemagne",
    "Marie Antoinette",
    "Meghan, Duchess of Sussex",
    "Michelangelo",
    "Najwa Nimri",
    "Hyun Bin",
    "Son Ye-jin",
    "George Soros",
    "Bruce Willis",
    "Kristen Stewart",
    "Kelly Preston",
    "Cleopatra",
    "Avicii",
    "Augustus",
    "Nicholas II",
    "Sandra Bullock",
    "Sean Connery",
    "River Phoenix",
    "Stephen King",
    "Kim Jong Il",
    "Zac Efron",
    "Saitō Dōsan",
    "J. K. Rowling",
    "Wentworth Miller",
    "Hayao Miyazaki",
    "Cameron Boyce",
    "Steven Spielberg",
    "Michael Douglas",
    "George V",
    "Jair Bolsonaro",
    "Matthew McConaughey",
    "Robert Pattinson",
    "Kim Yo-jong",
    "Jean-Claude Van Damme",
    "Ronald Reagan",
    "Michael J. Fox",
    "Melania Trump",
    "Orlando Bloom",
    "Saddam Hussein",
    "Frédéric Chopin",
    "Christopher Nolan",
    "Erling Haaland",
    "Immanuel Kant",
    "Mark Wahlberg",
    "Alan Turing",
    "Liam Neeson",
    "Mel Gibson",
    "Neil Armstrong",
    "Renée Zellweger",
    "Conor McGregor",
    "Josef Mengele",
    "Nicolas Cage",
    "Amy Winehouse",
    "Christian Bale",
    "Henry Cavill",
    "Warren Buffett",
    "Queen Elizabeth The Queen Mother",
    "Marlon Brando",
    "O. J. Simpson",
    "Adam Sandler",
    "Robert Lewandowski",
    "Osama bin Laden",
    "Mother Teresa",
    "Banksy",
    "Mustafa Kemal Atatürk",
    "Shaquille O'Neal",
    "Fyodor Dostoevsky",
    "Caitlyn Jenner",
    "Luke Perry",
    "Alba Flores",
    "Kylian Mbappé",
    "J. R. R. Tolkien",
    "Edward Snowden",
    "Dakota Johnson",
    "Simón Bolívar",
    "Jake Gyllenhaal",
    "Keira Knightley",
    "Ayrton Senna",
    "Chris Evans (actor)",
    "Yuri Gagarin",
    "Ip Man",
    "Maria Theresa",
    "Fidel Castro",
    "Mila Kunis",
    "Ernest Hemingway",
    "Anne, Princess Royal",
    "Monica Bellucci",
    "Ester Expósito",
    "Kate Winslet",
    "Louis de Funès",
    "René Descartes",
    "Charlie Sheen",
    "Khabib Nurmagomedov",
    "Cole Sprouse",
    "Kris Jenner",
    "Emilia Clarke",
    "Audrey Tang",
    "Johnny Cash",
    "Grigori Rasputin",
    "Daniel Craig",
    "Martin Scorsese",
    "Margaret Thatcher",
    "Jack Nicholson",
    "Albert Camus",
    "Morgan Freeman",
    "Úrsula Corberó",
    "Harrison Ford",
    "Chris Kyle",
    "Marco Polo",
    "Travis Scott",
    "George W. Bush",
    "Avicenna",
    "Leo Tolstoy",
    "Denzel Washington",
    "Heinrich Himmler",
    "Gal Gadot",
    "Prince Harry, Duke of Sussex",
    "Malcolm X",
    "Millie Bobby Brown",
    "Miley Cyrus",
    "Pep Guardiola",
    "Niki Lauda",
    "Olivia de Havilland",
    "Kim Il Sung",
    "Joseph Goebbels",
    "Jean-Jacques Rousseau",
    "George Washington",
    "Sergio Ramos",
    "Bernie Sanders",
    "Leon Trotsky",
    "Prince Andrew, Duke of York",
    "Adolf Eichmann",
    "Nicolaus Copernicus",
    "Anthony Hopkins",
    "Ronald Koeman",
    "Rachel McAdams",
    "Louis XVI",
    "Mary Magdalene",
    "Charles de Gaulle",
    "Franz Kafka",
    "Tutankhamun",
    "Alan Rickman",
    "Chester Bennington",
    "Winona Ryder",
    "Qin Shi Huang",
    "Grace Kelly",
    "Pythagoras",
    "Jason Momoa",
    "Freddie Highmore",
    "Andrea Bocelli",
    "Solomon",
    "Victor Hugo",
    "Cameron Diaz",
    "Osman I",
    "Louis Pasteur",
    "Recep Tayyip Erdoğan",
    "Bill Clinton",
    "Magnus Carlsen",
    "Chuck Norris",
    "John Cena",
    "Richard Nixon",
    "Benjamin Franklin",
    "Dante Alighieri",
    "Frank Sinatra",
    "Charles V, Holy Roman Emperor",
    "Alfred the Great",
    "Cara Delevingne",
    "Edward VII",
    "Stanley Kubrick",
    "Gabriel García Márquez",
    "Madam C. J. Walker",
    "Spartacus",
    "Magic Johnson",
    "Milla Jovovich",
    "Zodiac Killer",
    "Manuel Belgrano",
    "Agatha Christie",
    "The Weeknd",
    "Woody Allen",
    "Saladin",
    "Bong Joon-ho",
    "Cate Blanchett",
    "Rowan Atkinson",
    "Jennifer Connelly",
    "Yukio Mishima",
    "Anne Boleyn",
    "Benedict Cumberbatch",
    "Ashton Kutcher",
    "Marcus Aurelius",
    "Pierce Brosnan",
    "Peter the Great",
    "Nikita Khrushchev",
    "Nero",
    "Steve McQueen",
    "Gerard Butler",
    "Demi Moore",
    "Dakota Fanning",
    "Rami Malek",
    "Lee Teng-hui",
    "Queen Camilla",
    "Juan Carlos I",
    "Salma Hayek",
    "Oskar Schindler",
    "Sérgio Vieira de Mello",
    "Helena Bonham Carter",
    "Russell Crowe",
    "Otto von Bismarck",
    "Saint Peter",
    "Dalida",
    "Jacqueline Kennedy Onassis",
    "The Undertaker",
    "Joey King",
    "Jude Law",
    "Zayn Malik",
    "Mary I of England",
    "Alfred Hitchcock",
    "Nicki Minaj",
    "Jack the Ripper",
    "Novak Djokovic",
    "Eva Green",
    "Andrea Pirlo",
    "Edgar Allan Poe",
    "George Orwell",
    "Courteney Cox",
    "Muammar Gaddafi",
    "Emily Blunt",
    "Thierry Henry",
    "Bob Dylan",
    "Terence Hill",
    "Tyson Fury",
    "George Michael",
    "Reese Witherspoon",
    "Rooney Mara",
    "Guy Ritchie",
    "Charlie Hunnam",
    "Alain Delon",
    "Saoirse Ronan",
    "Karim Benzema",
    "Catherine Zeta-Jones",
    "Pyotr Ilyich Tchaikovsky",
    "Penélope Cruz",
    "Gianluigi Buffon",
    "Cory Monteith",
    "Ralph Fiennes",
    "Prince (musician)",
    "Kamala Harris",
    "Tina Turner",
    "Alexandra Daddario",
    "Floyd Mayweather Jr.",
    "Takuya Kimura",
    "Voltaire",
    "Johann Wolfgang von Goethe",
    "Cher",
    "Kevin Spacey",
    "Brittany Murphy",
    "Juice Wrld",
    "George H. W. Bush",
    "Astrid Lindgren",
    "Ted Kaczynski",
    "María Pedraza",
    "Samuel L. Jackson",
    "Rafael Nadal",
    "Gary Oldman",
    "Johan Cruyff",
    "Jimi Hendrix",
    "Commodus",
    "Edinson Cavani",
    "Carroll Shelby",
    "Liam Hemsworth",
    "Jodie Foster",
    "Miguel de Cervantes",
    "Andy Warhol",
    "Romy Schneider",
    "Brandon Lee",
    "Empress Elisabeth of Austria",
    "Hermann Göring",
    "Rachel Weisz",
    "Viggo Mortensen",
    "Theodore Roosevelt",
    "Oscar Wilde",
    "Jared Leto",
    "Stephen Curry",
    "Macaulay Culkin",
    "Kevin Costner",
    "Kourtney Kardashian",
    "Ozzy Osbourne",
    "Hugh Jackman",
    "Jimmy Carter",
    "Vajiralongkorn",
    "Ed Sheeran",
    "Gerard Piqué",
    "Chris Pratt",
    "Archimedes",
    "Antonio Banderas",
    "Jules Verne",
    "Sean Penn",
    "Felipe VI",
    "Phil Jackson",
    "Paolo Maldini",
    "Lindsay Lohan",
    "Ho Chi Minh",
    "Leonid Brezhnev",
    "John Locke",
    "Elle Fanning",
    "Catherine, Princess of Wales",
    "Cardi B",
    "50 Cent",
    "Constantine the Great",
    "Kaká",
    "Avril Lavigne",
    "Elsa Pataky",
    "Mohamed Salah",
    "Boris Yeltsin",
    "Alex Zanardi",
    "John D. Rockefeller",
    "Prince Edward, Duke of Edinburgh",
    "Elizabeth Taylor",
    "Channing Tatum",
    "Bud Spencer",
    "Shia LaBeouf",
    "Richard Gere",
    "Michelle Rodriguez",
    "Homer",
    "Irrfan Khan",
    "José Mourinho",
    "Jean-Paul Sartre",
    "Jean Castex",
    "Liv Tyler",
    "Hannibal",
    "Kirsten Dunst",
    "Antonio Vivaldi",
    "Florence Nightingale",
    "Ivanka Trump",
    "Jens Spahn",
    "Ri Sol-ju",
    "Lili Reinhart",
    "Max von Sydow",
    "Álvaro Morte",
    "Colin Farrell",
    "Ramesses II",
    "Kaley Cuoco",
    "Robert Redford",
    "Claude Monet",
    "Dwight D. Eisenhower",
    "Ignaz Semmelweis",
    "Gianni Versace",
    "Jordan Belfort",
    "Khloé Kardashian",
    "Jane Fonda",
    "Vanessa Hudgens",
    "Ewan McGregor",
    "Carl Jung",
    "Kate Beckinsale",
    "Jürgen Klopp",
    "Rupert Grint",
    "James Dean",
    "Jean Reno",
    "Sofía Vergara",
    "Laura Dern",
    "14th Dalai Lama",
    "Javier Bardem",
    "Priyanka Chopra",
    "Hirohito",
    "Emma Roberts",
    "James Franco",
    "Elizabeth Olsen",
    "Ian McKellen",
    "Eddie Murphy",
    "Michael Clarke Duncan",
    "Michel Piccoli",
    "Ali Khamenei",
    "Julian Assange",
    "Andrzej Duda",
    "Antoine Griezmann",
    "Edward Norton",
    "Brigitte Macron",
    "Édouard Philippe",
    "Rock Hudson",
    "Carrie Fisher",
    "Ivan the Terrible",
    "Amy Adams",
    "Cicero",
    "Elliot Page",
    "Maggie Smith",
    "Arthur Schopenhauer",
    "Bruno Mars",
    "Drake (musician)",
    "Lily James",
    "Lily Collins",
    "Chloë Grace Moretz",
    "Tones and I",
    "Brian May",
    "Helen Keller",
    "Daniel Day-Lewis",
    "Sharon Stone",
    "Justin Timberlake",
    "Matthew Perry",
    "Max Weber",
    "Rosa Parks",
    "Josip Broz Tito",
    "Alicia Vikander",
    "Jennifer Garner",
    "Christopher Lloyd",
    "Eva Braun",
    "Katherine Heigl",
    "Adam Driver",
    "Demi Lovato",
    "Uma Thurman",
    "Idris Elba",
    "Jane Austen",
    "Valentino Rossi",
    "Dustin Hoffman",
    "Ghislaine Maxwell",
    "Tim Burton",
    "Sebastian Vettel",
    "Ian Somerhalder",
    "Robert Koch",
    "Bryan Cranston",
    "Antoine de Saint-Exupéry",
    "Hans Christian Andersen",
    "Reinhard Heydrich",
    "Molière",
    "Phil Collins",
    "Thales of Miletus",
    "Stan Lee",
    "Jim Morrison",
    "Harry S. Truman",
    "Camila Cabello",
    "Rebecca Ferguson",
    "Christian Drosten",
    "Lana Del Rey",
    "Heidi Klum",
    "Michelle Pfeiffer",
    "Charles Dickens",
    "Jim Parsons",
    "Michelle Obama",
    "Louis XV",
    "Post Malone",
    "Drew Barrymore",
    "Nina Dobrev",
    "Richard Wagner",
    "Amanda Seyfried",
    "Vincent Cassel",
    "Vanessa Paradis",
    "Ursula von der Leyen",
    "Mick Jagger",
    "Eddie Redmayne",
    "Romelu Lukaku",
    "Brie Larson",
    "Franz Joseph I of Austria",
    "Brigitte Bardot",
    "Bashar al-Assad",
    "Chris Cornell",
    "Asa Butterfield",
    "Thomas Jefferson",
    "Jet Li",
    "David Lynch",
    "Luciano Pavarotti",
    "Jaden Smith",
    "Jamie Dornan",
    "Vivien Leigh",
    "Andrés Manuel López Obrador",
    "Jada Pinkett Smith",
    "Lisa Marie Presley",
    "Jessica Chastain",
    "Ben Stiller",
    "Pol Pot",
    "Rosamund Pike",
    "John Wayne",
    "Gordon Ramsay",
    "Dolph Lundgren",
    "James McAvoy",
    "Charles Bronson",
    "Eva Mendes",
    "Shawn Mendes",
    "Frank Abagnale",
    "Bernard Arnault",
    "Woody Harrelson",
    "Mac Miller",
    "Diane Kruger",
    "Kurt Russell",
    "Baruch Spinoza",
    "Maximilien Robespierre",
    "Philip Seymour Hoffman",
    "Mark Twain",
    "Qasem Soleimani",
    "Miguel Herrán",
    "Hailey Bieber",
    "Josh Brolin",
    "Robert F. Kennedy",
    "Michel Foucault",
    "Jaime Lorente",
    "Alec Baldwin",
    "Lyndon B. Johnson",
    "Luke Evans",
    "Hugh Grant",
    "Nick Jonas",
    "Lee Harvey Oswald",
    "Paris Hilton",
    "Elijah Wood",
    "Richard I of England",
    "Jennifer Grey",
    "Silvio Berlusconi",
    "Christoph Waltz",
    "John Forbes Nash Jr.",
    "Mario Casas",
    "Alexandre Dumas",
    "Natasha Richardson",
    "Hans Zimmer",
    "James Cameron",
    "Roberto Baggio",
    "Vasco da Gama",
    "Whoopi Goldberg",
    "Liza Minnelli",
    "Sia",
    "LP (singer)",
    "Chris Martin",
    "Janis Joplin",
    "Bella Thorne",
    "Emma Thompson",
    "Michael Bloomberg",
    "Stevie Wonder",
    "Halle Berry",
    "Richard Harris",
    "Roger Moore",
    "Paul Newman",
    "Matt LeBlanc",
    "Steve Carell",
    "Michael Caine",
    "Eric Cantona",
    "Stellan Skarsgård",
    "Yoko Ono",
    "Catherine de' Medici",
    "Enrique Iglesias",
    "Dmitry Medvedev",
    "Julianne Moore",
    "Henry Ford",
    "Sophie Turner",
    "Tobey Maguire",
    "Montesquieu",
    "Christina Aguilera",
    "Willem Dafoe",
    "Steve Irwin",
    "Blanca Suárez",
    "Valentina Tereshkova",
    "Zoë Kravitz",
    "Lavrentiy Beria",
    "Augusto Pinochet",
    "Henry VII of England",
    "Giannis Antetokounmpo",
    "Colin Firth",
    "Jeffrey Dean Morgan",
    "Jean-Paul Belmondo",
    "Itziar Ituño",
    "Émile Zola",
    "Haruki Murakami",
    "Fernando Alonso",
    "Jennie (singer)",
    "Maddie Ziegler",
    "Rachel Zegler",
    "Bella Hadid",
    "Max Verstappen",
    "Charles Leclerc",
    "Benny Andersson",
    "Anni-Frid Lyngstad",
    "Agnetha Fältskog",
    "Björn Ulvaeus",
]

export const pres_celebrities = [
    "Benny Andersson",
    "Anni-Frid Lyngstad",
    "Agnetha Fältskog",
    "Björn Ulvaeus",
    "Taylor Swift",
    "Albert Einstein",
    "Dua Lipa",
    "Madonna",
    "Elvis Presley",
    "Beyoncé",
    "Vincent van Gogh",
    "John Lennon",
    "Barack Obama",
    "Justin Bieber",
    "Rihanna",
    "Adele",
    "Emma Watson",
    "Zendaya",
    "Harry Styles",
    "Lionel Messi",
    "Neymar",
    "Serena Williams",
    "Roger Federer",
]