

export class CelebrityList {
   public celebrities : string[] = [
       "Taylor Swift",
       "Albert Einstein",
       "Dua Lipa",
       "Leonardo da Vinci",
       "Michael Jackson",
       "Madonna",
       "Elvis Presley",
       "Beyoncé",
       "Tom Cruise",
       "Angelina Jolie",
       "Brad Pitt",
       "Marilyn Monroe",
       "Barack Obama",
       "Oprah Winfrey",
       "Justin Bieber",
       "Rihanna",
       "Adele",
       "Emma Watson",
       "Kanye West",
       "Lady Gaga",
       "Jennifer Lopez",
       "Will Smith",
       "Britney Spears",
       "Johnny Depp",
       "Selena Gomez",
       "David Beckham",
       "Cristiano Ronaldo",
       "Katy Perry",
       "Steve Jobs",
       "Mark Zuckerberg",
       "Bill Gates",
       "Jeff Bezos",
       "Salvador Dalí",
       "Vincent van Gogh",
       "Walt Disney",
       "Angela Merkel",
       "Kylie Jenner",
       "Kim Kardashian",
       "Kendall Jenner",
       "Stephen Hawking",
       "Snoop Dogg",
       "Eminem",
       "Arnold Schwarzenegger",
       "Michael Jordan",
       "Muhammad Ali",
       "Celine Dion",
       "John Lennon",
       "Paul McCartney",
       "Ringo Starr",
       "George Harrison",
       "Bob Marley",
       "Elton John",
       "Freddie Mercury",
       "David Bowie",
       "Elizabeth II",
       "William, Prince of Wales",
       "Diana, Princess of Wales",
       "Nelson Mandela",
       "Malala Yousafzai",
       "Ellen DeGeneres",
       "Tom Hanks",
       "Robert Downey Jr.",
       "Jennifer Aniston",
       "Meryl Streep",
       "Leonardo DiCaprio",
       "Julia Roberts",
       "George Clooney",
       "Matt Damon",
       "Nicole Kidman",
       "Tom Hardy",
       "Daniel Radcliffe",
       "Emma Stone",
       "Scarlett Johansson",
       "Chris Hemsworth",
       "Jennifer Lawrence",
       "Gigi Hadid",
       "Zendaya",
       "Harry Styles",
       "Lionel Messi",
       "Neymar",
       "Serena Williams",
       "Roger Federer",
       "Lewis Hamilton",
       "Usain Bolt",
       "Tiger Woods",
       "Billie Eilish",
       "Ariana Grande",
       "Megan Fox",
       "Jessica Alba",
       "Gwyneth Paltrow",
       "Emmanuel Macron",
       "François Hollande",
       "Nicolas Sarkozy",
       "Carla Bruni",
       "Édith Piaf",
       "Marion Cotillard",
       "Ryan Reynolds",
       "Blake Lively",
       "Ryan Gosling",
       "Tom Holland",
       "Coco Chanel",
       "Christian Dior",
       "Jacques Brel",
       "Charles Aznavour"
   ];

   getRandom() : string {
       return this.celebrities[Math.floor(Math.random() * this.celebrities.length)];
   }

   toURL(celebrity : string) : string {
       return celebrity.replace(/ /g, "_");
   }
}